package org.example.lab1.mybatis.model;

public class Grupe {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GRUPE.ID
     *
     * @mbg.generated Sun Apr 04 10:32:52 EET 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GRUPE.PAVADINIMAS
     *
     * @mbg.generated Sun Apr 04 10:32:52 EET 2025
     */
    private String pavadinimas;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GRUPE.ID
     *
     * @return the value of PUBLIC.GRUPE.ID
     *
     * @mbg.generated Sun Apr 04 10:32:52 EET 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GRUPE.ID
     *
     * @param id the value for PUBLIC.GRUPE.ID
     *
     * @mbg.generated Sun Apr 04 10:32:52 EET 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GRUPE.PAVADINIMAS
     *
     * @return the value of PUBLIC.GRUPE.PAVADINIMAS
     *
     * @mbg.generated Sun Apr 04 10:32:52 EET 2025
     */
    public String getPavadinimas() {
        return pavadinimas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GRUPE.PAVADINIMAS
     *
     * @param pavadinimas the value for PUBLIC.GRUPE.PAVADINIMAS
     *
     * @mbg.generated Sun Apr 04 10:32:52 EET 2025
     */
    public void setPavadinimas(String pavadinimas) {
        this.pavadinimas = pavadinimas;
    }
}