package org.example.lab1.mybatis.dao;

import java.util.List;
import org.example.lab1.mybatis.model.Grupe;
import org.mybatis.cdi.Mapper;

@Mapper
public interface GrupeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GRUPE
     *
     * @mbg.generated Sun Apr 04 10:32:52 EET 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GRUPE
     *
     * @mbg.generated Sun Apr 04 10:32:52 EET 2025
     */
    int insert(Grupe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GRUPE
     *
     * @mbg.generated Sun Apr 04 10:32:52 EET 2025
     */
    Grupe selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GRUPE
     *
     * @mbg.generated Sun Apr 04 10:32:52 EET 2025
     */
    List<Grupe> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GRUPE
     *
     * @mbg.generated Sun Apr 04 10:32:52 EET 2025
     */
    int updateByPrimaryKey(Grupe record);
}